language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pybuilder
  - pip install -U pip setuptools
  - pip install pybuilder
  - pip install -U pip matplotlib
  - pip install opencv-python
  - pip install tensorflow
# command to run tests
script: pyb
